### ISSUE TITLE
Unable to launch latest git version

### ISSUE THREAD

**Issue by LukynZ** [smolleyes/gmediafinder2#4]
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/usr/bin/gmediafinder", line 22, in <module>
    from GmediaFinder import gmediafinder
  File "/usr/lib/python2.7/site-packages/GmediaFinder/gmediafinder.py", line 53, in <module>
    from GmediaFinder.lib.engines import Engines
ImportError: cannot import name Engines

**Comment by LukynZ** [comment]
Ok problem solved, I had missing pywebkitgtk package :)
